### ISSUE TITLE
Handle potential too long `LoadBalancer` name

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/cloud-provider-ironcore#457]
**What would you like to be added**:

We currently construct the `LoadBalancer` name from the cluster and `Service` name and add a UID suffix. This might result in a name which is longer than 64 chars.

Proposed solution:
Use a `GeneratedName` or `UID` of the `Service` when creating the `LoadBalancer` resource. Add to the `LoadBalancer` resource the cluster name and `Service` name as annotations in order to "find" it when running `EnsureLoadbalancer`.

Backwards compatibility concerns:
We might want to keep backwards compatibility by first trying to get the "old" name. If that can't be find we transition to the new generated name based handling of `LoadBalancers`.

**Comment by ushabelgur** [comment]
It will be better if we can derive LoadBalancer from the service name as per the `GetLoadBalancerName()` method signature as well GetLoadBalancerName(ctx context.Context, clusterName string, service *v1.Service) other cloud providers also following similar approach
https://github.com/kubernetes/cloud-provider-openstack/blob/ffd6a76bfabb83d00926dc049c0b6ea28f88142f/pkg/openstack/loadbalancer.go#L366
https://github.com/kubernetes/cloud-provider-aws/blob/d12b519d94e4ea9085af38a071a3d73ce946b147/pkg/providers/v1/aws.go#L2561
So going ahead with populating name with service UID approach
